name: frp Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/frp.yml'
      - 'frp/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/frp.yml'
      - 'frp/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push frps
        uses: docker/build-push-action@v3
        with:
          context: ./frp
          push: true
          build-args: |
            FRP_VERSION=0.45.0
            BUILD_TARGET=frpc
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frpc:latest
      -
        name: Build and push frps
        uses: docker/build-push-action@v3
        with:
          context: ./frp
          push: true
          build-args: |
            FRP_VERSION=0.45.0
            BUILD_TARGET=frps
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frps:latest
